version: "3"
services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend